### ISSUE TITLE
Getting CrashloopBackOff status while deploying the pod in K8s

### ISSUE THREAD

**Issue by vrathore18** [DataReply/alertmanager-sns-forwarder#8]
I am getting CrashloopBackOff status. I am using the same deployment yaml as per the project. Below is the part where I have added my env specific details.

```
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: alertmanager-sns-forwarder
      annotations:
        iam.amazonaws.com/role: cluster-test-Role
    spec:
      restartPolicy: Always
      containers:
      - name: alertmanager-sns-forwarder
        image: datareply/alertmanager-sns-forwarder
        imagePullPolicy: Always
        # You can also specify arguments
        # args: ["--addr=:9087", "--debug", "--arn-prefix=<some_prefix>"]
        env:
          - name: AWS_REGION
            value: "us-east-1"
          - name: AWS_DEFAULT_REGION
            value: "us-east-1"
          - name: SNS_FORWARDER_ADDRESS
            value: "9087"        
          - name: SNS_FORWARDER_DEBUG
            value: "false"
          - name: SNS_FORWARDER_ARN_PREFIX
            value: "arn:aws:sns:us-east-1:8xxxxxxxx:SYSTEST_K8S_ALERTS"
```
I have checked the logs but I don't find any issue there.

```
kubectl logs -f alertmanager-sns-forwarder-f8b4546b7-97c55 -n monitoring
time="2019-01-09T07:16:19Z" level=info msg="listening on9087"
```

**Comment by olgierdg** [comment]
Could you check without setting the SNS_FORWARDER_ADDRESS env var, since you're using the default port number anyway, or setting it to ":9087"? I think the lack of colon is the problem, in the table in the Arguments section of the doc the default value for this setting is also shown including the colon, so the custom value should follow the same convention.

**Comment by vrathore18** [comment]
@olgierdg  Thanks!!!! the crashloopBackOff is changed to running but now I am started getting an error.

[GIN] 2019/01/09 - 12:02:37 | 503 |  57.860312ms | 10.10.10.29:51772 |   POST    /alert/SYSTEST_K8S_ALERTS
time="2019-01-09T12:02:37Z" level=warning msg="AuthorizationError: User: arn:aws:sts::8xxxxxx:assumed-role/cluster-test-Role/i-089aba4XXXXXX is not authorized to perform: SNS:Publish on resource: arn:aws:sns:us-east-1:8xxxxxxxxx:SYSTEST_K8S_ALERTSSYSTEST_K8S_ALERTS\n\tstatus code: 403, request id: c9cfa6d2-3ee7-551b-8631-f27ddbfa4082"

I am using below code in alertmanager.yaml 
```
receivers:
- name: 'sns-forwarder'
  slack_configs:
  - api_url: https://hooks.slack.com/services/TF90Yxxxx/BF86PP4xxxxxxxxxxxxxxxx
    channel: '#k8'
    icon_emoji: ':bell:'
    send_resolved: true
    text: "<!channel> \nsummary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}"
  webhook_configs:
  - send_resolved: True
    url: http://alertmanager-sns-forwarder-svc.monitoring:9087/alert/SYSTEST_K8S_ALERTS
```
I am using monitoring in place of default because I deployed the pod in monitoring namespace alertmanager-sns-forwarder-svc.monitoring:9087

please suggest what could be the issue. Thank for helping again
